#!/usr/bin/env bash

MOTIF_PROJECT_ROOT="${MOTIF_PROJECT_ROOT:-/workspace/motif-3-mixed-ds4}"
MOTIF_FAST_ROOT="${MOTIF_FAST_ROOT:-/motif3}"
MOTIF_HF_CACHE="${MOTIF_HF_CACHE:-${MOTIF_FAST_ROOT}/hf-cache}"
MOTIF_SOURCE_REPO="Motif-Technologies/Motif-3"
MOTIF_SOURCE_REV="ccceb1a5fd7b5eb32e47841216b3caf5666c07bc"
MOTIF_SOURCE_SNAPSHOT="${MOTIF_SOURCE_SNAPSHOT:-${MOTIF_FAST_ROOT}/source-final}"
MOTIF_ARTIFACT_DIR="${MOTIF_ARTIFACT_DIR:-${MOTIF_FAST_ROOT}/artifacts}"
MOTIF_LLAMA_CPP="${MOTIF_LLAMA_CPP:-${MOTIF_FAST_ROOT}/llama.cpp}"
MOTIF_DS4="${MOTIF_DS4:-/workspace/ds4}"

export MOTIF_PROJECT_ROOT MOTIF_FAST_ROOT MOTIF_HF_CACHE
export MOTIF_SOURCE_REPO MOTIF_SOURCE_REV MOTIF_SOURCE_SNAPSHOT
export MOTIF_ARTIFACT_DIR MOTIF_LLAMA_CPP MOTIF_DS4
